### PR TITLE
Scrolling and high-dpi support

### PR DESCRIPTION
**Pull request by mdimura**
I have added some hight-dpi support to the program and also added scrolling via arrow keys.

### CODE REVIEW

**Comment by Kaffeine** [comment]
Take a note that I'm already and yet not one of the project developer, so it would be better to wait for @crackedmind for the actual authoritarian review :).

**Comment by mdimura** [comment]
Sure, Thanks for your suggestions!

**Comment by mdimura** [comment]
I implemented the before mentioned suggestions in `c8fbeaa`

**Comment by mdimura** [comment]
Oops, that bug was not supposed to get through.

**Comment by crackedmind** [comment]
I can test this a little bit later. Seems ok to me.

**Comment by mdimura** [comment]
@crackedmind  Is there any way I could contact you directly, i.e. skype/viber/...? I have some enhancements in mind and would like to ask for your opinion on what are the better ways of implementation. I also wanted to ask about h3m format.

**Comment by crackedmind** [comment]
Check email, i sent you an invitation to gitter chat.

**Pull request merged**
